runtime: php
env: flex

runtime_config:
  operating_system: "ubuntu22"
  document_root: public

build_env_variables:
  GOOGLE_COMPOSER_VERSION: 2.2.1

service: api

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 100

env_variables:
  FINDIP_TOKEN: "a4b542192dd34a8682ec1c71f942b01a"

  # follow the part of the tutorial on setting up your SQL database
  DB_CONNECTION: mysql
  DB_HOST: 172.19.16.3
  DB_DATABASE: butler1970dotcom
  DB_USERNAME: root
  DB_PASSWORD: "@~vf6vm<rt^?1usp"

  # Put production environment variables here.
  APP_DEBUG: true
  APP_ENV: production
  APP_KEY: base64:uwGp1ZpPJZYhigUAaHnDjWV6ubmEB1TsGerae+0RQQs=
  APP_NAME: "Laravel"

  LOG_LEVEL: debug
