runtime: php
env: flex

runtime_config:
  operating_system: "ubuntu22"
  document_root: public

build_env_variables:
  GOOGLE_COMPOSER_VERSION: 2.2.1

service: api

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 100

env_variables:
  # follow the part of the tutorial on setting up your SQL database
  DB_CONNECTION: mysql
  DB_HOST: 172.19.16.3
  DB_DATABASE: butler1970dotcom
  DB_USERNAME: root
  DB_PASSWORD: "@~vf6vm<rt^?1usp"
  #DB_SOCKET: /cloudsql/savvy-temple-393819:us-central1:butler1970dotcom

  # Put production environment variables here.
  APP_DEBUG: true
  APP_ENV: production
  APP_KEY: base64:uwGp1ZpPJZYhigUAaHnDjWV6ubmEB1TsGerae+0RQQs=
  APP_NAME: "Laravel"

  LOG_LEVEL: debug

#we need this for the flex environment
beta_settings:
  # for Cloud SQL, set this value to the Cloud SQL connection name,
  # e.g. "project:region:cloudsql-instance"
  cloud_sql_instances: savvy-temple-393819:us-central1:butler1970dotcom
